# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 50

development:
  <<: *default
  database: meter_development

test:
  <<: *default
  database: meter_test

production:
  <<: *default
  database: meter_prod
